name: Test Hello World Action

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run hello world action
        id: greeting
        uses: ./hello-world-docker-action
        with:
          name: 'GitHub Actions'
          message: 'Welcome to'
      
      - name: Display output
        run: echo "Output: ${{ steps.greeting.outputs.greeting }}"
